version: '2'


services:
  service1:
    build:
      context: .
      dockerfile: DockerfileLs
    container_name: service1
    environment:
      - PORT=35001
    ports:
      - "35001:35001"
  service2:
      build:
        context: .
        dockerfile: DockerfileLs
      container_name: service2
      environment:
        - PORT=35002
      ports:
        - "35002:35002"
  service3:
      build:
        context: .
        dockerfile: DockerfileLs
      container_name: service3
      environment:
        - PORT=35003
      ports:
        - "35003:35003"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - PORT=45000
    ports:
      - "8080:45000"
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: