version: '2'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - PORT=45000
    ports:
      - "8080:45000"
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: